### PR TITLE
[release/2.3] Added force_shape_pad option to avoid compute bound optimizations for test_pad_mm.py

### PR DESCRIPTION
**Pull request by iupaikov-amd**
This fixes:
test_pad_mm_dyn_m
test_pad_mm_dyn_n
test_pad_mm_dyn_k

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [93960cf202a5f82c07138e9f7c97ac052408a562](https://github.com/ROCm/pytorch/commit/93960cf202a5f82c07138e9f7c97ac052408a562) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1654/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1654/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [93960cf202a5f82c07138e9f7c97ac052408a562](https://github.com/ROCm/pytorch/commit/93960cf202a5f82c07138e9f7c97ac052408a562) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1654/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1654/2/artifact)

**Comment by pruthvistony** [comment]
@iupaikov-amd ,
Can we upstream this change.

**Review by pruthvistony — APPROVED** [review]

**Comment by iupaikov-amd** [comment]
@pruthvistony there is no need, for some reason the platform specific parts of code behave very different from older builds with 2.3 release. If you run any image from pytorch upstream with ROCm the tests won't fail. I'm currently collecting data so we can fine tune it later with Jack.

**Pull request merged**
