### PR TITLE
[rocm6.3_internal_testing] [NO CP] Added ignore to cuda driver check code to disable warnings for ROCm builds

### PR DESCRIPTION
**Pull request by iupaikov-amd**
Fixes #9579

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [42195525b7648ebb7971d32e64ef7af720f1b90d](https://github.com/ROCm/pytorch/commit/42195525b7648ebb7971d32e64ef7af720f1b90d) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1642/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1642/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [42195525b7648ebb7971d32e64ef7af720f1b90d](https://github.com/ROCm/pytorch/commit/42195525b7648ebb7971d32e64ef7af720f1b90d) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1642/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1642/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [42195525b7648ebb7971d32e64ef7af720f1b90d](https://github.com/ROCm/pytorch/commit/42195525b7648ebb7971d32e64ef7af720f1b90d) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1642/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1642/3/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [42195525b7648ebb7971d32e64ef7af720f1b90d](https://github.com/ROCm/pytorch/commit/42195525b7648ebb7971d32e64ef7af720f1b90d) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1642/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1642/4/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [42195525b7648ebb7971d32e64ef7af720f1b90d](https://github.com/ROCm/pytorch/commit/42195525b7648ebb7971d32e64ef7af720f1b90d) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1642/5//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1642/5/artifact)

**Review by pruthvistony — APPROVED** [review]

**Pull request merged**
