### PR TITLE
Bump to AOTriton 0.7.1b

### PR DESCRIPTION
**Pull request by xinyazhang**
A cherry-picked version of https://github.com/pytorch/pytorch/pull/134498 for rocm6.3_internal_testing

### CODE REVIEW

**Comment by pruthvistony** [comment]
LGTM.
But want to wait till - https://github.com/pytorch/pytorch/pull/134498 is merged. So that we can cherry-pick all changes after review.

**Comment by rocm-mici** [comment]
Jenkins build for [30525a1b547dbede736a9ae3c0fe87c0501a4773](https://github.com/ROCm/pytorch/commit/30525a1b547dbede736a9ae3c0fe87c0501a4773) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1572/5//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1572/5/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [30525a1b547dbede736a9ae3c0fe87c0501a4773](https://github.com/ROCm/pytorch/commit/30525a1b547dbede736a9ae3c0fe87c0501a4773) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1572/6//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1572/6/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [30525a1b547dbede736a9ae3c0fe87c0501a4773](https://github.com/ROCm/pytorch/commit/30525a1b547dbede736a9ae3c0fe87c0501a4773) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1572/7//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1572/7/artifact)

**Review by pruthvistony — APPROVED** [review]

**Pull request merged**
