### PR TITLE
AOTriton: select gpu targets according to PYTORCH_ROCM_ARCH

### PR DESCRIPTION
**Pull request by xinyazhang**
Due to the landing of SWDEV-476126, Navi 3x is unsupported for now.

Fixes #GPUAI-2940

### CODE REVIEW

**Review by vickytsang — APPROVED** [review]

**Comment by rocm-mici** [comment]
Jenkins build for [e7a4114f0b896a5740f4027c49cf89ddb223eb8a](https://github.com/ROCm/pytorch/commit/e7a4114f0b896a5740f4027c49cf89ddb223eb8a) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1643/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1643/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [e7a4114f0b896a5740f4027c49cf89ddb223eb8a](https://github.com/ROCm/pytorch/commit/e7a4114f0b896a5740f4027c49cf89ddb223eb8a) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1643/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1643/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [e7a4114f0b896a5740f4027c49cf89ddb223eb8a](https://github.com/ROCm/pytorch/commit/e7a4114f0b896a5740f4027c49cf89ddb223eb8a) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1643/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1643/3/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [e7a4114f0b896a5740f4027c49cf89ddb223eb8a](https://github.com/ROCm/pytorch/commit/e7a4114f0b896a5740f4027c49cf89ddb223eb8a) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1643/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1643/4/artifact)

**Comment by jithunnair-amd** [comment]
@xinyazhang Can you please file an upstream PR for this?

**Comment by xinyazhang** [comment]
@jithunnair-amd https://github.com/pytorch/pytorch/pull/139432
We need to ask @vickytsang to sign the CLA

**Pull request merged**
