### PR TITLE
aotriton build should honor PYTORCH_ROCM_ARCH flag (GPUAI-2940)

### PR DESCRIPTION
**Pull request by vickytsang**
Fixes GPUAI-2940

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [fabb97af03e4f559dede4418eb7309b291060677](https://github.com/ROCm/pytorch/commit/fabb97af03e4f559dede4418eb7309b291060677) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1634/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1634/1/artifact)

**Comment by pruthvistony** [comment]
@vickytsang ,
We want to avoid AOTriton build from source. Worst case on the fall back scenario we should build only current gpu arch.

**Review by xinyazhang — CHANGES_REQUESTED** [review]
Need some changes. Notably the Navi32 part (yeah I know they have no fundamental differences but tuning database for Navi32 is not there)

**Review by xinyazhang — APPROVED** [review]

**Comment by rocm-mici** [comment]
Jenkins build for [b05add347f2c92ee7297a6f943015fbf9d919b60](https://github.com/ROCm/pytorch/commit/b05add347f2c92ee7297a6f943015fbf9d919b60) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1634/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1634/2/artifact)

**Comment by xinyazhang** [comment]
Hi @vickytsang
We ususally do not target ROCM/main branch. I'm re-targeting `rocm6.3_internal_testing` now

**Pull request closed without merging**
