### PR TITLE
[ROCm] Set thread work size to 8 for elementwise kernels

### PR DESCRIPTION
**Pull request by jerrymannil**
This improves elementwise kernel performances on MI300 gpus.

Co-author: @akadutta

### CODE REVIEW

**Comment by jerrymannil** [comment]
test_unary_unfunc, test_binary_ufunc are passing 
test_transformers also is passing, except have 6 preexisting failures;

**Comment by rocm-mici** [comment]
Jenkins build for [d33205785a2d6458032045206b0ab45dc932729b](https://github.com/ROCm/pytorch/commit/d33205785a2d6458032045206b0ab45dc932729b) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1734/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1734/1/artifact)

Detected error during Pytorch building: 
```
  580 | #define DEPRECATED(msg) __attribute__ ((deprecated(msg)))
      |                                         ^
1 warning generated when compiling for gfx908.
[7982/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_spherical_bessel_j0.hip.o
[7983/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o
FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o 
cd /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn && /opt/conda/envs/py_3.10/bin/cmake -E make_directory /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/. && /opt/conda/envs/py_3.10/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/./torch_hip_generated_flash_api.hip.o -P /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o.cmake
In file included from /var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip:57:
/var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/aotriton_adapter.h:120:10: error: no matching constructor for initialization of 'aotriton::TensorView<0>'
  120 |   return aotriton::TensorView<0>(reinterpret_cast<intptr_t>(q.data_ptr()),
      |          ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
Should this enabling patch - https://github.com/ROCm/pytorch/commit/840589ace7fb9a851613ab32e762d691c2c051d9 also be combined with this PR.

**Comment by pruthvistony** [comment]
> Should this enabling patch - [840589a](https://github.com/ROCm/pytorch/commit/840589ace7fb9a851613ab32e762d691c2c051d9) also be combined with this PR.

To be worked next.

**Comment by rocm-mici** [comment]
Created branch [release/2.5_cherry-pick_pr-1734](https://github.com/ROCm/pytorch/tree/release/2.5_cherry-pick_pr-1734) and https://github.com/ROCm/pytorch/pull/1798

**Pull request merged**
