### PR TITLE
Fix 491578 issue - socket_power metric AMDSMI and clockrate function using correct dictionary key

### PR DESCRIPTION
**Pull request by amd-sriram**
Fixes 491578
makes test_clock_speed and test_power_draw subtests in test_cuda PASS

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [447a565b07811d3458d7e6552322b39594789fa4](https://github.com/ROCm/pytorch/commit/447a565b07811d3458d7e6552322b39594789fa4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1673/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1673/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [447a565b07811d3458d7e6552322b39594789fa4](https://github.com/ROCm/pytorch/commit/447a565b07811d3458d7e6552322b39594789fa4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1673/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1673/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [447a565b07811d3458d7e6552322b39594789fa4](https://github.com/ROCm/pytorch/commit/447a565b07811d3458d7e6552322b39594789fa4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1673/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1673/3/artifact)

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@jataylo ,
FYI, to be aware of amdsmi related changes.

**Pull request merged**
