### PR TITLE
IFU-rocm6.4_internal_testing-2024-10-11

### PR DESCRIPTION
**Pull request by jithunnair-amd**
### After consolidation:

Only differences vs the changes in that branch:
```
diff -r ./.ci/docker/requirements-ci.txt /tmp/pytorch/.ci/docker/requirements-ci.txt
17a18,23
> sympy==1.12.1
> #Description: Python library for symbolic mathematics
> # installed before coremltools to avoid installation of greater sympy version
> #Pinned versions: 1.12.1
> #test that import:
>
325,326c331,332
< sympy==1.12.1 ; python_version == "3.8"
< sympy==1.13.1 ; python_version >= "3.9"
---
> # sympy==1.12.1 ; python_version == "3.8"
> # sympy==1.13.1 ; python_version >= "3.9"

diff -r ./requirements.txt /tmp/pytorch/requirements.txt
12,13c12
< sympy==1.12.1 ; python_version == "3.8"
< sympy==1.13.1 ; python_version >= "3.9"
---
> sympy==1.12.1 ; python_version >= "3.8"
diff -r ./test/inductor/test_fp8.py /tmp/pytorch/test/inductor/test_fp8.py
158a159
>
```
### Rebased onto latest rocm6.4_internal_testing

Decided to drop commits b3a7516c0a56d45e9df38edadcec55fafc5ea0a2 and 56ec3c7942a80c318d03c5c2ea41b5c50d7e83b0 because they are out-of-sync with upstream, and Prachi is preparing upstream PR anyway, which we should cherry-pick instead

### Consolidated commits again

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [abff42144686a9d74004f3255a23371ed81fded4](https://github.com/ROCm/pytorch/commit/abff42144686a9d74004f3255a23371ed81fded4) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1612/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1612/1/artifact)

**Comment by dnikolaev-amd** [comment]
success build
http://rocm-ci.amd.com/job/mainline-framework-pytorch-2.4-ub20-py3.9-ci/24/

**Comment by jithunnair-amd** [comment]
Rebased on to rocm6.4_internal_testing as of 2024/10/11, so updated title

**Comment by rocm-mici** [comment]
Jenkins build for [dd97a567e690c15c63062d240bc5464dfe110b7b](https://github.com/ROCm/pytorch/commit/dd97a567e690c15c63062d240bc5464dfe110b7b) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1612/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1612/3/artifact)

**Pull request merged**
