### PR TITLE
Skipped certain distributed tests

### PR DESCRIPTION
**Pull request by BLOrange-AMD**

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Review by jithunnair-amd — CHANGES_REQUESTED** [review]
@BLOrange-AMD This looks to be the same change that was put into release/2.0 via https://github.com/ROCm/pytorch/commit/7902926cf39565f3883bbe587486bdacef9ef569. Shouldn't we just cherry-pick that entire change into release/2.1?

**Comment by BLOrange-AMD** [comment]
@jithunnair-amd The commit in release/2.0 disabled more unit tests (five different tests). In release/2.1 branch, only two unit test fail which are excluded in this PR.

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd The commit in release/2.0 disabled more unit tests (five different tests). In release/2.1 branch, only two unit test fail which are excluded in this PR.

Yes, but the same issue is linked to all 5 unit tests, so I'm skeptical/confused why we don't see the other 3 failing? Can you please check locally so we don't have to put the same fix for them later?

**Comment by BLOrange-AMD** [comment]
@jithunnair-amd In release/2.1 branch, these three tests are commenting out: https://github.com/ROCm/pytorch/blob/release/2.1/torch/testing/_internal/distributed/distributed_test.py#L4888

**Review by jithunnair-amd — APPROVED** [review]

**Pull request merged**
