### PR TITLE
[release/2.4] AMDSMI/layernorm cherry picks

### PR DESCRIPTION
**Pull request by jataylo**
Cherry pick amdsmi fix: https://github.com/pytorch/pytorch/commit/04f569a5246850b57748a86fd16a5bae02bd9d72
Cherry pick layer_norm accuracy fix: https://github.com/pytorch/pytorch/commit/001f7366a71cd19e4b460624ab76053225c8676e

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [2fe3720921182bd31460b0f80fde3b3bbc4ac91c](https://github.com/ROCm/pytorch/commit/2fe3720921182bd31460b0f80fde3b3bbc4ac91c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1765/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1765/1/artifact)

Detected error during Pytorch building: 
```
[7942/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_modified_bessel_k0.hip.o
[7943/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_fused_adam_amsgrad_impl.hip.o
[7944/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_scaled_modified_bessel_k0.hip.o
[7945/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_fused_adam_impl.hip.o
[7946/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention.hip.o
FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention.hip.o /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention.hip.o 
cd /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip && /opt/conda/envs/py_3.10/bin/cmake -E make_directory /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/. && /opt/conda/envs/py_3.10/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/./torch_hip_generated_attention.hip.o -P /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention.hip.o.cmake
In file included from /var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/attention.hip:84:
/var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/aotriton_adapter.h:120:10: error: no matching constructor for initialization of 'aotriton::TensorView<0>'
  120 |   return aotriton::TensorView<0>(reinterpret_cast<intptr_t>(q.data_ptr()),
      |          ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Review by pruthvistony — APPROVED** [review]

**Comment by inemankov** [comment]
!cherry-pick --onto rocm6.4_internal_testing release/2.5 unknown_branch

**Comment by rocm-mici** [comment]
Can't perform the cherry-pick keyword: unexpected error

**Comment by inemankov** [comment]
!cherry-pick --onto rocm6.3_internal_testing release/2.5 unknown_branch

**Comment by rocm-mici** [comment]
Created branch [rocm6.3_internal_testing_cherry-pick_pr-1765](https://github.com/ROCm/pytorch/tree/rocm6.3_internal_testing_cherry-pick_pr-1765) and https://github.com/ROCm/pytorch/pull/1779Created branch [release/2.5_cherry-pick_pr-1765](https://github.com/ROCm/pytorch/tree/release/2.5_cherry-pick_pr-1765) and https://github.com/ROCm/pytorch/pull/1780

Target branch ```unknown_branch``` doesn't exist

**Comment by inemankov** [comment]
!cherry-pick --onto rocm6.3_internal_testing release/2.5

**Comment by jithunnair-amd** [comment]
!cherry-pick --onto rocm6.2_internal_testing release/2.5.4.5

**Comment by rocm-mici** [comment]
Created branch [rocm6.2_internal_testing_cherry-pick_pr-1765](https://github.com/ROCm/pytorch/tree/rocm6.2_internal_testing_cherry-pick_pr-1765) and https://github.com/ROCm/pytorch/pull/1783

Target branch ```release/2.5.4.5``` doesn't exist

**Pull request merged**
