### PR TITLE
[release/2.4] AOTriton build refactor: download binary from github, NO BUILD FROM SOURCE option

### PR DESCRIPTION
**Pull request by jithunnair-amd**
*    AOTriton build refactor: download binary from github, NO BUILD FROM SOURCE option    
*    Copy AOTRITON_INSTALLED_PREFIX/* to torch/, Otherwise bdist_wheel will miss libaotriton_v2.so
*    Move all aotriton_version.txt info to aotriton.cmake
*    Consider ROCm version to pick up right tarball
*    Supply ROCM versions and SHA256 checksums as lists.
 
Changes cherry-picked from https://github.com/pytorch/pytorch/pull/137443

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [a3ef66bc6f4f3b4f6749e026d09855267dd95e00](https://github.com/ROCm/pytorch/commit/a3ef66bc6f4f3b4f6749e026d09855267dd95e00) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/3/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/4/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/5//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/5/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/6//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/6/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/7//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/7/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/8//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/8/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/9//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/9/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/10//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/10/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/11//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/11/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/12//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/12/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/13//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/13/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/14//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/14/artifact)

Detected error during Pytorch building: 
```
[7937/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_modified_bessel_k0.hip.o
[7938/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_modified_bessel_i0.hip.o
[7939/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_WeightNorm.hip.o
[7940/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_modified_bessel_k1.hip.o
[7941/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o
FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o 
cd /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn && /opt/conda/envs/py_3.10/bin/cmake -E make_directory /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/. && /opt/conda/envs/py_3.10/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/./torch_hip_generated_flash_api.hip.o -P /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/flash_attn/torch_hip_generated_flash_api.hip.o.cmake
In file included from /var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/flash_attn/flash_api.hip:57:
/var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/aotriton_adapter.h:120:10: error: no matching constructor for initialization of 'aotriton::TensorView<0>'
  120 |   return aotriton::TensorView<0>(reinterpret_cast<intptr_t>(q.data_ptr()),
      |          ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rocm-mici** [comment]
Jenkins build for [c30d565bdde8592331f374c3bc9de3fffc157f97](https://github.com/ROCm/pytorch/commit/c30d565bdde8592331f374c3bc9de3fffc157f97) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1626/16//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1626/16/artifact)

Detected error during Pytorch building: 
```
/var/lib/jenkins/pytorch/aten/src/ATen/native/hip/DistributionTemplates.h:186:17: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
/var/lib/jenkins/pytorch/aten/src/ATen/native/hip/DistributionTemplates.h:186:17: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
12 warnings generated when compiling for gfx942.
[7983/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_UnaryGeometricAcoshKernel.hip.o
[7984/8635] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention_backward.hip.o
FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention_backward.hip.o /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention_backward.hip.o 
cd /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip && /opt/conda/envs/py_3.10/bin/cmake -E make_directory /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/. && /opt/conda/envs/py_3.10/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/./torch_hip_generated_attention_backward.hip.o -P /var/lib/jenkins/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/transformers/hip/torch_hip_generated_attention_backward.hip.o.cmake
In file included from /var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/attention_backward.hip:49:
/var/lib/jenkins/pytorch/aten/src/ATen/native/transformers/hip/aotriton_adapter.h:120:10: error: no matching constructor for initialization of 'aotriton::TensorView<0>'
  120 |   return aotriton::TensorView<0>(reinterpret_cast<intptr_t>(q.data_ptr()),
      |          ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jithunnair-amd** [comment]
Closing in favor of https://github.com/ROCm/pytorch/pull/1691

**Pull request closed without merging**
