### PR TITLE
[release/2.2] Fixed error string assertion in test_invalid_devices

### PR DESCRIPTION
**Pull request by iupaikov-amd**
Fixes #8974

### CODE REVIEW

**Comment by iupaikov-amd** [comment]
Different error message here, this can probably cause issues if this branch gets built on later rocm distributions.

**Comment by rocm-mici** [comment]
Jenkins build for [b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc](https://github.com/ROCm/pytorch/commit/b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1617/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1617/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc](https://github.com/ROCm/pytorch/commit/b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1617/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1617/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc](https://github.com/ROCm/pytorch/commit/b7f91d67df0d9440bfaac7ff9499aa456a7ef9bc) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1617/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1617/3/artifact)

**Review by pruthvistony — APPROVED** [review]

**Pull request merged**
