### PR TITLE
[release/2.3] AOTriton build refactor: download binary from github, NO BUILD FROM SOURCE option

### PR DESCRIPTION
**Pull request by jithunnair-amd**
*    AOTriton build refactor: download binary from github, NO BUILD FROM SOURCE option    
*    Copy AOTRITON_INSTALLED_PREFIX/* to torch/, Otherwise bdist_wheel will miss libaotriton_v2.so
*    Move all aotriton_version.txt info to aotriton.cmake
*    Consider ROCm version to pick up right tarball
*    Supply ROCM versions and SHA256 checksums as lists.
 
Changes cherry-picked from https://github.com/pytorch/pytorch/pull/137443

### CODE REVIEW

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/1//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/1/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/2//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/2/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as SUCCESS
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/3//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/3/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/4//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/4/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/5//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/5/artifact)

**Comment by rocm-mici** [comment]
Jenkins build for [94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c](https://github.com/ROCm/pytorch/commit/94e2aab0ed57b03b73a85fb83cc45e9fe1ed028c) commit finished as FAILURE
Links: [Blue Ocean view](http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-pipeline/detail/PR-1623/6//pipeline) / [Build artifacts](http://ml-ci-internal.amd.com:8080/job/pytorch/job/pytorch-ci-pipeline/job/PR-1623/6/artifact)

**Comment by jithunnair-amd** [comment]
Closing in favor of https://github.com/ROCm/pytorch/pull/1690

**Pull request closed without merging**
